Nearest trainers
Fiu-Fit/Back pull request #1
Opened 2023-05-26 19:55 UTC by ianshih2003

2023-05-27 19:01 UTC, rplatini requested changes

2023-05-27 23:31 UTC, ManuSanchez02 requested changes

2023-05-27 23:31 UTC, ManuSanchez02 commented on app/users-service/src/modules/user-location/schema/user-location.schema.ts
> +}
El type puede ser un enum?

2023-05-28 01:28 UTC, ianshih2003 commented on app/users-service/src/modules/user-location/schema/user-location.schema.ts
> +}
Considerando que solo va a ser un solo valor, no lo haria

2023-05-28 02:36 UTC, rplatini approved these changes

2023-05-28 04:23 UTC, ManuSanchez02 commented on app/users-service/src/modules/user-location/schema/user-location.schema.ts
> +}
Y para que existe entonces?

2023-05-28 16:21 UTC, ianshih2003 commented on app/users-service/src/modules/user-location/schema/user-location.schema.ts
> +}
Porque asi se define una ubicacion geologica en mongo, si en algun momento integramos poligonos, ahi si tendriamos un enum

2023-05-28 16:25 UTC, ManuSanchez02 commented on app/users-service/src/modules/user-location/schema/user-location.schema.ts
> +}
Ok

2023-05-29 23:19 UTC, merged