PIN Confirmation
Fiu-Fit/Back pull request #29
Opened 2023-06-30 19:09 UTC by ianshih2003

2023-06-30 19:23 UTC, ManuSanchez02 requested changes

2023-06-30 19:23 UTC, ManuSanchez02 commented on app/users-service/src/modules/auth/auth.service.ts
> +        body: `Tu codigo de registracion es: ${confirmationPIN}`,
Codigo de registracion queda raro, le pondria codigo de confirmacion

2023-06-30 19:23 UTC, ManuSanchez02 commented on app/users-service/src/modules/auth/auth.service.ts
> +        from: 'whatsapp:+14155238886',
El numero ese es constante?

2023-06-30 19:23 UTC, ManuSanchez02 commented on app/users-service/src/modules/auth/auth.service.ts
> +    console.log('Whatsapp notification sent succesfully!');
No se si lo dejaste intencional o no

2023-06-30 19:23 UTC, ManuSanchez02 commented on app/users-service/src/modules/auth/dto/admin-register-request.dto.ts
> +  phoneNumber?: string;
Los admins tmb tienen codigo de confirmacion/numero de tel?

2023-07-02 16:36 UTC, ianshih2003 commented on app/users-service/src/modules/auth/dto/admin-register-request.dto.ts
> +  phoneNumber?: string;
No

2023-07-02 16:36 UTC, ianshih2003 commented on app/users-service/src/modules/auth/auth.service.ts
> +    console.log('Whatsapp notification sent succesfully!');
Intencional

2023-07-02 16:36 UTC, ianshih2003 commented on app/users-service/src/modules/auth/auth.service.ts
> +        from: 'whatsapp:+14155238886',
Si, no lo voy a cambiar

2023-07-02 16:37 UTC, ianshih2003 commented on app/users-service/src/modules/auth/auth.service.ts
> +        body: `Tu codigo de registracion es: ${confirmationPIN}`,
```suggestion
        body: `Tu codigo de confirmacion es: ${confirmationPIN}`,
```

2023-07-02 16:40 UTC, ianshih2003 commented on app/users-service/src/modules/auth/dto/admin-register-request.dto.ts
> +  phoneNumber?: string;
```suggestion
```

2023-07-02 16:42 UTC, ManuSanchez02 approved these changes

2023-07-02 21:56 UTC, merged