Services
Fiu-Fit/Back pull request #6
Opened 2023-06-12 18:08 UTC by ianshih2003

2023-06-12 21:59 UTC, ManuSanchez02 requested changes

2023-06-12 21:59 UTC, ManuSanchez02 commented on app/api-gateway/src/modules/auth/auth.module.ts
> +      },
Le agregaste el return por algo en particular?

2023-06-12 21:59 UTC, ManuSanchez02 commented on app/service-registry/package.json
> +    "common:install": "yarn add @fiu-fit/common@git@github.com:Fiu-Fit/common.git && yarn"
Ya no hace falta common install

2023-06-12 21:59 UTC, ManuSanchez02 commented on app/service-registry/utils/api-key-guard.ts
> +    return apiKey === process.env.PROGRESS_API_KEY;
Por que progress_api_key?

2023-06-12 21:59 UTC, ManuSanchez02 commented on app/workout-service/yarn.lock
Lo mismo que te dije del otro yarn lock

2023-06-13 17:31 UTC, ianshih2003 commented on app/api-gateway/src/modules/service-registry/service-registry.controller.ts
> +  }
Cuales

2023-06-13 17:38 UTC, ianshih2003 commented on app/api-gateway/src/modules/auth/auth.module.ts
> +      },
porque tiene que devolver una configuracion

2023-06-13 17:40 UTC, ManuSanchez02 commented on app/api-gateway/src/modules/auth/auth.module.ts
> +      },
Pero no podias dejarlo como estaba tipo `() => valor_de_retorno`?

2023-06-13 17:48 UTC, ianshih2003 commented on app/api-gateway/src/modules/service-registry/service-registry.controller.ts
> +  }
si decis los cruds estan integrados en server controller

2023-06-13 17:52 UTC, ManuSanchez02 approved these changes

2023-06-13 17:53 UTC, merged